sequenceDiagram
    participant ST as ShapeTester
    participant R as r1 : Rectangle
    participant T as t1 : Triangle

    ST->>ST: compareShapes(r1, t1)

    ST->>R: calcArea()
    R->>R: height * width
    R-->>ST: 50

    ST->>T: calcArea()
    T->>T: (height * width) / 2
    T-->>ST: 50

    ST->>ST: 50 == 50
    ST-->>ST: true
