classDiagram
    direction LR
    class Book {
        <<abstract>>
        -isbn String
        -title String
        +calculateDuration() int*
    }
    class PhysicalBook {
        -location String
        +calculateDuration() int
    }
    class EBook {
        -fileFormat String
        +calculateDuration() int
    }
    PhysicalBook --|> Book : inheritance
    EBook --|> Book : inheritance
